### ISSUE TITLE
Runtime error when reproducing: size mismatch

### ISSUE THREAD

**Issue by KarryBanana** [ReliableCoding/REPEAT#1]
Hello! I was running some experiments with your work REPEAT. 
When I run `bash fintune.sh`, I got this Runtime error which occurred in `clone/CodeBert/model.py line 21`: `RuntimeError: The expanded size of the tensor (800) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [16, 800].  Tensor sizes: [1, 514] `
I check the `config.json` from pretrained model `microsoft/codebert-base` and find `max_position_embeddings` is 400, while the shape of `input_ids` is `[16, 800]`.

![image](https://github.com/ReliableCoding/REPEAT/assets/25265710/a4acc15e-9621-4ada-87fe-53358afc8d66)
![image](https://github.com/ReliableCoding/REPEAT/assets/25265710/46b81bf5-2931-4933-8524-83d6a1571ab9)

I just wonder have you ever had a similar problem and Is it possible to change the ·max_position_embeddings to `800` ?

Best wish!

**Comment by shuzhenggao** [comment]
Hello, thanks so much for your notice. In our experiment, we set the block_size to 256 to avoid this problem. It seems that we forget to change this when preparing replication package.
